export const FETCH_API="FETCH_API";
export const DELETE_PRODUCTS="DELETE_PRODUCTS";
export const UPDATE_PRODUCTS="UPDATE_PRODUCTS";
export const ADD_PRODUCTS="ADD_PRODUCTS";
export const EDDIT_PRODUCTS="EDDIT_PRODUCTS";
export const FETCH_API_PRODUCT="FETCH_API_PRODUCT";