version: '3.7'

services:
  user_dashboard_opay:
    build: 
      context: ../../
      dockerfile: "deploy/docker/Dockerfile"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/conf.d/default.conf
