export const GET_LAMBOR_AVENTADOR_REQUEST = "GET_LAMBOR_AVENTADOR_REQUEST";
export const GET_LAMBOR_AVENTADOR_SUCCESS = "GET_LAMBOR_AVENTADOR_SUCCESS";

export const DELETE_LAMBOR_AVENTADOR_REQUEST = "DELETE_LAMBOR_AVENTADOR_REQUEST";
export const DELETE_LAMBOR_AVENTADOR_SUCCESS = "DELETE_LAMBOR_AVENTADOR_SUCCESS";

export const ADD_LAMBOR_AVENTADOR_REQUEST = "ADD_LAMBOR_AVENTADOR_REQUEST";
export const ADD_LAMBOR_AVENTADOR_SUCCESS = "ADD_LAMBOR_AVENTADOR_SUCCESS";

export const GETEDIT_LAMBOR_AVENTADOR_REQUEST = "GETEDIT_LAMBOR_AVENTADOR_REQUEST";
export const GETEDIT_LAMBOR_AVENTADOR_SUCCESS = "GETEDIT_LAMBOR_AVENTADOR_SUCCESS";

export const UPDATE_LAMBOR_AVENTADOR_REQUEST = "UPDATE_LAMBOR_AVENTADOR_REQUEST";
export const UPDATE_LAMBOR_AVENTADOR_SUCCESS = "UPDATE_LAMBOR_AVENTADOR_SUCCESS";


//
export const GET_LAMBOR_SUV_REQUEST = "GET_LAMBOR_SUV_REQUEST";
export const GET_LAMBOR_SUV_SUCCESS = "GET_LAMBOR_SUV_SUCCESS";

export const DELETE_LAMBOR_SUV_REQUEST = "DELETE_LAMBOR_SUV_REQUEST";
export const DELETE_LAMBOR_SUV_SUCCESS = "DELETE_LAMBOR_SUV_SUCCESS";

export const ADD_LAMBOR_SUV_REQUEST = "ADD_LAMBOR_SUV_REQUEST";
export const ADD_LAMBOR_SUV_SUCCESS = "ADD_LAMBOR_SUV_SUCCESS";

export const GETEDIT_LAMBOR_SUV_REQUEST = "GETEDIT_LAMBOR_SUV_REQUEST";
export const GETEDIT_LAMBOR_SUV_SUCCESS = "GETEDIT_LAMBOR_SUV_SUCCESS";

export const UPDATE_LAMBOR_SUV_REQUEST = "UPDATE_LAMBOR_SUV_REQUEST";
export const UPDATE_LAMBOR_SUV_SUCCESS = "UPDATE_LAMBOR_SUV_SUCCESS";


//
export const GET_LAMBOR_HARUCAN_REQUEST = "GET_LAMBOR_HARUCAN_REQUEST";
export const GET_LAMBOR_HARUCAN_SUCCESS = "GET_LAMBOR_HARUCAN_SUCCESS";

export const DELETE_LAMBOR_HARUCAN_REQUEST = "DELETE_LAMBOR_HARUCAN_REQUEST";
export const DELETE_LAMBOR_HARUCAN_SUCCESS = "DELETE_LAMBOR_HARUCAN_SUCCESS";

export const ADD_LAMBOR_HARUCAN_REQUEST = "ADD_LAMBOR_HARUCAN_REQUEST";
export const ADD_LAMBOR_HARUCAN_SUCCESS = "ADD_LAMBOR_HARUCAN_SUCCESS";

export const GETEDIT_LAMBOR_HARUCAN_REQUEST = "GETEDIT_LAMBOR_HARUCAN_REQUEST";
export const GETEDIT_LAMBOR_HARUCAN_SUCCESS = "GETEDIT_LAMBOR_HARUCAN_SUCCESS";

export const UPDATE_LAMBOR_HARUCAN_REQUEST = "UPDATE_LAMBOR_HARUCAN_REQUEST";
export const UPDATE_LAMBOR_HARUCAN_SUCCESS = "UPDATE_LAMBOR_HARUCAN_SUCCESS";