export const GET_TOYOTA_SADAN_REQUEST = "GET_TOYOTA_SADAN_REQUEST";
export const GET_TOYOTA_SADAN_SUCCESS = "GET_TOYOTA_SADAN_SUCCESS";

export const DELETE_TOYOTA_SADAN_REQUEST = "DELETE_TOYOTA_SADAN_REQUEST";
export const DELETE_TOYOTA_SADAN_SUCCESS = "DELETE_TOYOTA_SADAN_SUCCESS";

export const ADD_TOYOTA_SADAN_REQUEST = "ADD_TOYOTA_SADAN_REQUEST";
export const ADD_TOYOTA_SADAN_SUCCESS = "ADD_TOYOTA_SADAN_SUCCESS";

export const GETEDIT_TOYOTA_SADAN_REQUEST = "GETEDIT_TOYOTA_SADAN_REQUEST";
export const GETEDIT_TOYOTA_SADAN_SUCCESS = "GETEDIT_TOYOTA_SADAN_SUCCESS";


export const UPDATE_TOYOTA_SADAN_REQUEST = "UPDATE_TOYOTA_SADAN_REQUEST";
export const UPDATE_TOYOTA_SADAN_SUCCESS = "UPDATE_TOYOTA_SADAN_SUCCESS";





//
export const GET_TOYOTA_SUVTOYOTAS_REQUEST = "GET_TOYOTA_SUVTOYOTAS_REQUEST";
export const GET_TOYOTA_SUVTOYOTAS_SUCCESS = "GET_TOYOTA_SUVTOYOTAS_SUCCESS";

export const DELETE_TOYOTA_SUVTOYOTAS_REQUEST = "DELETE_TOYOTA_SUVTOYOTAS_REQUEST";
export const DELETE_TOYOTA_SUVTOYOTAS_SUCCESS = "DELETE_TOYOTA_SUVTOYOTAS_SUCCESS";

export const ADD_TOYOTA_SUVTOYOTAS_REQUEST = "ADD_TOYOTA_SUVTOYOTAS_REQUEST";
export const ADD_TOYOTA_SUVTOYOTAS_SUCCESS = "ADD_TOYOTA_SUVTOYOTAS_SUCCESS";

export const GETEDIT_TOYOTA_SUVTOYOTAS_REQUEST = "GETEDIT_TOYOTA_SUVTOYOTAS_REQUEST";
export const GETEDIT_TOYOTA_SUVTOYOTAS_SUCCESS = "GETEDIT_TOYOTA_SUVTOYOTAS_SUCCESS";

export const UPDATE_TOYOTA_SUVTOYOTAS_REQUEST = "UPDATE_TOYOTA_SUVTOYOTAS_REQUEST";
export const UPDATE_TOYOTA_SUVTOYOTAS_SUCCESS = "UPDATE_TOYOTA_SUVTOYOTAS_SUCCESS";







//
export const GET_TOYOTA_DADUNG_REQUEST = "GET_TOYOTA_DADUNG_REQUEST";
export const GET_TOYOTA_DADUNG_SUCCESS = "GET_TOYOTA_DADUNG_SUCCESS";

export const DELETE_TOYOTA_DADUNG_REQUEST = "DELETE_TOYOTA_DADUNG_REQUEST";
export const DELETE_TOYOTA_DADUNG_SUCCESS = "DELETE_TOYOTA_DADUNG_SUCCESS";

export const ADD_TOYOTA_DADUNG_REQUEST = "ADD_TOYOTA_DADUNG_REQUEST";
export const ADD_TOYOTA_DADUNG_SUCCESS = "ADD_TOYOTA_DADUNG_SUCCESS";

export const GETEDIT_TOYOTA_DADUNG_REQUEST = "GETEDIT_TOYOTA_DADUNG_REQUEST";
export const GETEDIT_TOYOTA_DADUNG_SUCCESS = "GETEDIT_TOYOTA_DADUNG_SUCCESS";

export const UPDATE_TOYOTA_DADUNG_REQUEST = "UPDATE_TOYOTA_DADUNG_REQUEST";
export const UPDATE_TOYOTA_DADUNG_SUCCESS = "UPDATE_TOYOTA_DADUNG_SUCCESS";
