export const GET_MER_SALOONS_REQUEST = "GET_MER_SALOONS_REQUEST";
export const GET_MER_SALOONS_SUCCESS = "GET_MER_SALOONS_SUCCESS";

export const DELETE_MER_SALOONS_REQUEST = "DELETE_MER_SALOONS_REQUEST";
export const DELETE_MER_SALOONS_SUCCESS = "DELETE_MER_SALOONS_SUCCESS";

export const ADD_MER_SALOONS_REQUEST = "ADD_MER_SALOONS_REQUEST";
export const ADD_MER_SALOONS_SUCCESS = "ADD_MER_SALOONS_SUCCESS";

export const GETEDIT_MER_SALOONS_REQUEST = "GETEDIT_MER_SALOONS_REQUEST";
export const GETEDIT_MER_SALOONS_SUCCESS = "GETEDIT_MER_SALOONS_SUCCESS";

export const UPDATE_MER_SALOONS_REQUEST = "UPDATE_MER_SALOONS_REQUEST";
export const UPDATE_MER_SALOONS_SUCCESS = "UPDATE_MER_SALOONS_SUCCESS";




//

export const GET_MER_SUV_REQUEST = "GET_MER_SUV_REQUEST";
export const GET_MER_SUV_SUCCESS = "GET_MER_SUV_SUCCESS";

export const DELETE_MER_SUV_REQUEST = "DELETE_MER_SUV_REQUEST";
export const DELETE_MER_SUV_SUCCESS = "DELETE_MER_SUV_SUCCESS";

export const ADD_MER_SUV_REQUEST = "ADD_MER_SUV_REQUEST";
export const ADD_MER_SUV_SUCCESS = "ADD_MER_SUV_SUCCESS";

export const GETEDIT_MER_SUV_REQUEST = "GETEDIT_MER_SUV_REQUEST";
export const GETEDIT_MER_SUV_SUCCESS = "GETEDIT_MER_SUV_SUCCESS";

export const UPDATE_MER_SUV_REQUEST = "UPDATE_MER_SUV_REQUEST";
export const UPDATE_MER_SUV_SUCCESS = "UPDATE_MER_SUV_SUCCESS";



//
export const GET_MER_COPEE_REQUEST = "GET_MER_COPEE_REQUEST";
export const GET_MER_COPEE_SUCCESS = "GET_MER_COPEE_SUCCESS";

export const DELETE_MER_COPEE_REQUEST = "DELETE_MER_COPEE_REQUEST";
export const DELETE_MER_COPEE_SUCCESS = "DELETE_MER_COPEE_SUCCESS";

export const ADD_MER_COPEE_REQUEST = "ADD_MER_COPEE_REQUEST";
export const ADD_MER_COPEE_SUCCESS = "ADD_MER_COPEE_SUCCESS";

export const GETEDIT_MER_COPEE_REQUEST = "GETEDIT_MER_COPEE_REQUEST";
export const GETEDIT_MER_COPEE_SUCCESS = "GETEDIT_MER_COPEE_SUCCESS";

export const UPDATE_MER_COPEE_REQUEST = "UPDATE_MER_COPEE_REQUEST";
export const UPDATE_MER_COPEE_SUCCESS = "UPDATE_MER_COPEE_SUCCESS";

